# Generated by Django 5.0.1 on 2024-02-29 11:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0006_chatusers_is_staff_chatusers_is_superuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatusers',
            options={'verbose_name': 'ChatUser', 'verbose_name_plural': 'ChatUsers'},
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'verbose_name': 'Conversation', 'verbose_name_plural': 'Conversations'},
        ),
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterField(
            model_name='conversation',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
